name: Deploy Frontend

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test
      
    - name: Build
      run: npm run build
      env:
        VITE_APP_TITLE: ${{ secrets.VITE_APP_TITLE }}
        VITE_APP_DESCRIPTION: ${{ secrets.VITE_APP_DESCRIPTION }}
        VITE_DOMAIN: ${{ secrets.VITE_DOMAIN }}
        VITE_STRAPI_URL: ${{ secrets.VITE_STRAPI_URL }}
        VITE_STRAPI_TOKEN: ${{ secrets.VITE_STRAPI_TOKEN }}
        
    - name: Deploy to VPS
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        source: "dist/*"
        target: "/var/www/analytechs/"
        strip_components: 1
        
    - name: Execute deployment script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /var/www/analytechs
          sudo systemctl reload nginx